services:
  web:
    build: .
    container_name: cloudnest_web
    command: gunicorn src.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "9000:8000"
    env_file:
      - .env.docker
    environment:
      - DJANGO_ENV=docker
    depends_on:
      - db
    entrypoint: ["/app/entrypoint.sh"]

  db:
    image: postgres:15
    container_name: cloudnest_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"   # host 5433 â†’ container 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
